adminDozent_index:
    path:     /
    defaults: { _controller: "HZraumReservierungBundle:Dozent:index" }
    methods:  GET

adminDozent_show:
    path:     /{id}/show
    defaults: { _controller: "HZraumReservierungBundle:Dozent:show" }
    methods:  GET

adminDozent_new:
    path:     /new
    defaults: { _controller: "HZraumReservierungBundle:Dozent:new" }
    methods:  [GET, POST]

adminDozent_edit:
    path:     /{id}/edit
    defaults: { _controller: "HZraumReservierungBundle:Dozent:edit" }
    methods:  [GET, POST]

adminDozent_delete:
    path:     /{id}/delete
    defaults: { _controller: "HZraumReservierungBundle:Dozent:delete" }
    methods:  DELETE
