adminRaum_index:
    path:     /
    defaults: { _controller: "HZraumReservierungBundle:Raum:index" }
    methods:  GET

adminRaum_show:
    path:     /{id}/show
    defaults: { _controller: "HZraumReservierungBundle:Raum:show" }
    methods:  GET

adminRaum_new:
    path:     /new
    defaults: { _controller: "HZraumReservierungBundle:Raum:new" }
    methods:  [GET, POST]

adminRaum_edit:
    path:     /{id}/edit
    defaults: { _controller: "HZraumReservierungBundle:Raum:edit" }
    methods:  [GET, POST]

adminRaum_delete:
    path:     /{id}/delete
    defaults: { _controller: "HZraumReservierungBundle:Raum:delete" }
    methods:  DELETE
