adminReservierung_index:
    path:     /
    defaults: { _controller: "HZraumReservierungBundle:Reservierung:index" }
    methods:  GET

adminReservierung_show:
    path:     /{id}/show
    defaults: { _controller: "HZraumReservierungBundle:Reservierung:show" }
    methods:  GET

adminReservierung_new:
    path:     /new
    defaults: { _controller: "HZraumReservierungBundle:Reservierung:new" }
    methods:  [GET, POST]

adminReservierung_edit:
    path:     /{id}/edit
    defaults: { _controller: "HZraumReservierungBundle:Reservierung:edit" }
    methods:  [GET, POST]

adminReservierung_delete:
    path:     /{id}/delete
    defaults: { _controller: "HZraumReservierungBundle:Reservierung:delete" }
    methods:  DELETE
