<?php

namespace HZ\raumReservierungBundle\Repository;

/**
 * ConfirmationPinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmationPinRepository extends \Doctrine\ORM\EntityRepository
{
}
