<?php

namespace HZ\raumReservierungBundle\Repository;

/**
 * DozentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DozentRepository extends \Doctrine\ORM\EntityRepository
{
}
