<?php

namespace HZ\raumReservierungBundle\Repository;

/**
 * GebaeudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GebaeudeRepository extends \Doctrine\ORM\EntityRepository
{
}
