<?php

namespace HZ\raumReservierungBundle\Repository;

/**
 * kontaktRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class kontaktRepository extends \Doctrine\ORM\EntityRepository
{
}
