<?php

namespace HZ\raumReservierungBundle\Repository;

/**
 * ReservierungRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservierungRepository extends \Doctrine\ORM\EntityRepository
{
}
