<?php

namespace Proxies\__CG__\HZ\raumReservierungBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Raum extends \HZ\raumReservierungBundle\Entity\Raum implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'id', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'nummer', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'name', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'frei', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'sitzplatze', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'beamer', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'steckdose', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'usbAnschluss', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'image', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'gebaeude', 'reservierungAdmin'];
        }

        return ['__isInitialized__', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'id', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'nummer', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'name', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'frei', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'sitzplatze', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'beamer', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'steckdose', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'usbAnschluss', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'image', '' . "\0" . 'HZ\\raumReservierungBundle\\Entity\\Raum' . "\0" . 'gebaeude', 'reservierungAdmin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Raum $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNummer($nummer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNummer', [$nummer]);

        return parent::setNummer($nummer);
    }

    /**
     * {@inheritDoc}
     */
    public function getNummer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNummer', []);

        return parent::getNummer();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setGebaeude(\HZ\raumReservierungBundle\Entity\Gebaeude $gebaeude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGebaeude', [$gebaeude]);

        return parent::setGebaeude($gebaeude);
    }

    /**
     * {@inheritDoc}
     */
    public function getGebaeude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGebaeude', []);

        return parent::getGebaeude();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(\HZ\raumReservierungBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeamer($beamer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeamer', [$beamer]);

        return parent::setBeamer($beamer);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeamer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeamer', []);

        return parent::getBeamer();
    }

    /**
     * {@inheritDoc}
     */
    public function setSteckdose($steckdose)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSteckdose', [$steckdose]);

        return parent::setSteckdose($steckdose);
    }

    /**
     * {@inheritDoc}
     */
    public function getSteckdose()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSteckdose', []);

        return parent::getSteckdose();
    }

    /**
     * {@inheritDoc}
     */
    public function setSitzplätze($sitzplätze)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitzplätze', [$sitzplätze]);

        return parent::setSitzplätze($sitzplätze);
    }

    /**
     * {@inheritDoc}
     */
    public function getSitzplätze()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitzplätze', []);

        return parent::getSitzplätze();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsbAnschluss($usbAnschluss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsbAnschluss', [$usbAnschluss]);

        return parent::setUsbAnschluss($usbAnschluss);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsbAnschluss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsbAnschluss', []);

        return parent::getUsbAnschluss();
    }

    /**
     * {@inheritDoc}
     */
    public function setSitzplatze($sitzplatze)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitzplatze', [$sitzplatze]);

        return parent::setSitzplatze($sitzplatze);
    }

    /**
     * {@inheritDoc}
     */
    public function getSitzplatze()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitzplatze', []);

        return parent::getSitzplatze();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrei($frei)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrei', [$frei]);

        return parent::setFrei($frei);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrei()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrei', []);

        return parent::getFrei();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservierungAdmin(\HZ\raumReservierungBundle\Entity\ReservierungAdmin $reservierungAdmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservierungAdmin', [$reservierungAdmin]);

        return parent::addReservierungAdmin($reservierungAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservierungAdmin(\HZ\raumReservierungBundle\Entity\ReservierungAdmin $reservierungAdmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservierungAdmin', [$reservierungAdmin]);

        return parent::removeReservierungAdmin($reservierungAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservierungAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservierungAdmin', []);

        return parent::getReservierungAdmin();
    }

}
